### ISSUE TITLE
[Feature Request]: please support deno

### ISSUE THREAD

**Issue by izumkineno** [farm-fe/farm#2073]
### What problem does this feature solve?

~/Desktop/izum_C/toolbox> deno i                                                                01/23/2025 10:05:49 上午Warning The following packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed:
┠─ npm:core-js@3.40.0
┃
┠─ This may cause the packages to not work correctly.
┖─ To run lifecycle scripts, use the `--allow-scripts` flag with `deno install`:
deno install --allow-scripts=npm:core-js@3.40.0
~/Desktop/izum_C/toolbox> deno run dev                                                          01/23/2025 10:05:54 上午Task dev farm
[ Farm ] Using config file at C:\Users\CEO\Desktop\izum_C\toolbox\farm.config.ts
[ building ] ⠂ transform (19) \0plugin-vue:export-helper
[ Farm ] Error: Failed to start the server
Caused by: Error: Can not resolve `vue` from src/main.ts.
Original error: None.

Potential Causes:
1. The file that `vue` points to does not exist.
2. Install it first if `vue` is an dependency from node_modules, if you are using pnpm refer to [https://pnpm. io/faq#pnpm-does-not-work-with-your-project-here] for solutions.
3.  If `vue` is a alias, make sure your alias config is correct.

Can not resolve `vue` from src/App.vue.
Original error: None.

Potential Causes:
1. The file that `vue` points to does not exist.
2. Install it first if `vue` is an dependency from node_modules, if you are using pnpm refer to [https://pnpm. io/faq#pnpm-does-not-work-with-your-project-here] for solutions.
3.  If `vue` is a alias, make sure your alias config is correct.

Can not resolve `vue` from src/App.vue.
Original error: None.

Potential Causes:
1. The file that `vue` points to does not exist.
2. Install it first if `vue` is an dependency from node_modules, if you are using pnpm refer to [https://pnpm. io/faq#pnpm-does-not-work-with-your-project-here] for solutions.
3.  If `vue` is a alias, make sure your alias config is correct.

Can not resolve `vue` from src/components/Greet.vue.
Original error: None.

Potential Causes:
1. The file that `vue` points to does not exist.
2. Install it first if `vue` is an dependency from node_modules, if you are using pnpm refer to [https://pnpm. io/faq#pnpm-does-not-work-with-your-project-here] for solutions.
3.  If `vue` is a alias, make sure your alias config is correct.

Can not resolve `vue` from src/components/Greet.vue.
Original error: None.

Potential Causes:
1. The file that `vue` points to does not exist.
2. Install it first if `vue` is an dependency from node_modules, if you are using pnpm refer to [https://pnpm. io/faq#pnpm-does-not-work-with-your-project-here] for solutions.
3.  If `vue` is a alias, make sure your alias config is correct.

Can not resolve `vue` from src/components/Greet.vue.
Original error: None.

Potential Causes:
1. The file that `vue` points to does not exist.
2. Install it first if `vue` is an dependency from node_modules, if you are using pnpm refer to [https://pnpm. io/faq#pnpm-does-not-work-with-your-project-here] for solutions.
3.  If `vue` is a alias, make sure your alias config is correct.

Can not resolve `@tauri-apps/api/tauri` from src/components/Greet.vue.
Original error: None.

Potential Causes:
1. The file that `@tauri-apps/api/tauri` points to does not exist.
2. Install it first if `@tauri-apps/api/tauri` is an dependency from node_modules, if you are using pnpm refer to [https://pnpm. io/faq#pnpm-does-not-work-with-your-project-here] for solutions.
3.  If `@tauri-apps/api/tauri` is a alias, make sure your alias config is correct.

at logError (file:///C:/Users/CEO/Desktop/izum_C/toolbox/node_modules/.deno/@farmfe+core@1.6.6/node_modules/@farmfe/core/dist/server/error.js:74:15)
at Server.compile (file:///C:/Users/CEO/Desktop/izum_C/toolbox/node_modules/.deno/@farmfe+core@1.6.6/node_modules/@farmfe/core/dist/server/index.js:63:29)
at async Server. listen (file:///C:/Users/CEO/Desktop/izum_C/toolbox/node_modules/.deno/@farmfe+core@1.6.6/node_modules/@farmfe/core/dist/server/index.js:45:9)
at async start (file:///C:/Users/CEO/Desktop/izum_C/toolbox/node_modules/.deno/@farmfe+core@1.6.6/node_modules/@farmfe/core/dist/index.js:35:9)
at async handleAsyncOperationErrors (file:///C:/Users/CEO/Desktop/izum_C/toolbox/node_modules/.deno/@farmfe+cli@1.0.4/node_modules/@farmfe/cli/dist/utils.js:111:9)

### What does the proposed API look like?

'deno run dev' works properly

**Comment by wre232114** [comment]
Looks like the dependencies under node_modules can not be found, do you install dependencies?

**Comment by fu050409** [comment]
Could you please provide your deno config file?

**Comment by izumkineno** [comment]
> Could you please provide your deno config file?

config file?  I don't edit any config

**Comment by izumkineno** [comment]
> Looks like the dependencies under node_modules can not be found, do the dependencies installed?

     __  ,
 .--()°'.' Welcome to Nushell,
'|, . ,'   based on the nu language,
 !_-(_\    where all data is structured!

Our Documentation is located at https://nushell.sh
Tweet us at @nu_shell
Learn how to remove this at: https://nushell.sh/book/configuration.html#remove-welcome-message

It's been this long since Nushell's first commit:
5yrs 8months 12days 13hrs 7mins 54secs 201ms 516µs 900ns
Startup Time: 51ms 453µs 100ns

~/Desktop/izum_C> npm create farm@latest                                                        01/23/2025 02:07:06 下午

 ⚡ Welcome To Farm !

✔ Project name · farm-project
✔ Select a framework: · Vue3 - (https://vuejs.org/)

 ✔️ Template copied Successfully!


 >  Initial Farm Project created successfully ✨ ✨

    cd farm-project

    npm install

    npm run dev

~/Desktop/izum_C> cd farm-project\                                                              01/23/2025 02:07:15 下午~/Desktop/izum_C/farm-project> deno i                                                           01/23/2025 02:07:20 下午Warning The following packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed:
┠─ npm:core-js@3.40.0
┃
┠─ This may cause the packages to not work correctly.
┖─ To run lifecycle scripts, use the `--allow-scripts` flag with `deno install`:
   deno install --allow-scripts=npm:core-js@3.40.0
~/Desktop/izum_C/farm-project> deno install --allow-scripts=npm:core-js@3.40.0                  01/23/2025 02:07:25 下午~/Desktop/izum_C/farm-project> deno i                                                           01/23/2025 02:07:31 下午
~/Desktop/izum_C/farm-project> deno run dev                                                     01/23/2025 02:07:36 下午
Task dev farm start
[ Farm ] Using config file at C:\Users\CEO\Desktop\izum_C\farm-project\farm.config.ts
[ building ] ⠄ transform (19) src/components/HelloWorld.vue?vue&type=style&index=0&scoped=e17ea971&lang.css             [ Farm ] Error: Failed to start the server
Caused by: Error: Can not resolve `vue` from src/index.ts.
Original error: None.

Potential Causes:
1.The file that `vue` points to does not exist.
2.Install it first if `vue` is an dependency from node_modules, if you are using pnpm refer to [https://pnpm.io/faq#pnpm-does-not-work-with-your-project-here] for solutions.
3. If `vue` is a alias, make sure your alias config is correct.

Can not resolve `vue` from src/App.vue.
Original error: None.

Potential Causes:
1.The file that `vue` points to does not exist.
2.Install it first if `vue` is an dependency from node_modules, if you are using pnpm refer to [https://pnpm.io/faq#pnpm-does-not-work-with-your-project-here] for solutions.
3. If `vue` is a alias, make sure your alias config is correct.

Can not resolve `vue` from src/App.vue.
Original error: None.

Potential Causes:
1.The file that `vue` points to does not exist.
2.Install it first if `vue` is an dependency from node_modules, if you are using pnpm refer to [https://pnpm.io/faq#pnpm-does-not-work-with-your-project-here] for solutions.
3. If `vue` is a alias, make sure your alias config is correct.

Can not resolve `vue` from src/components/HelloWorld.vue.
Original error: None.

Potential Causes:
1.The file that `vue` points to does not exist.
2.Install it first if `vue` is an dependency from node_modules, if you are using pnpm refer to [https://pnpm.io/faq#pnpm-does-not-work-with-your-project-here] for solutions.
3. If `vue` is a alias, make sure your alias config is correct.
Can not resolve `vue` from src/components/HelloWorld.vue.
Original error: None.

Potential Causes:
1.The file that `vue` points to does not exist.
2.Install it first if `vue` is an dependency from node_modules, if you are using pnpm refer to [https://pnpm.io/faq#pnpm-does-not-work-with-your-project-here] for solutions.
3. If `vue` is a alias, make sure your alias config is correct.

Can not resolve `vue` from src/components/HelloWorld.vue.
Original error: None.

Potential Causes:
1.The file that `vue` points to does not exist.
2.Install it first if `vue` is an dependency from node_modules, if you are using pnpm refer to [https://pnpm.io/faq#pnpm-does-not-work-with-your-project-here] for solutions.
3. If `vue` is a alias, make sure your alias config is correct.

    at logError (file:///C:/Users/CEO/Desktop/izum_C/farm-project/node_modules/.deno/@farmfe+core@1.6.6/node_modules/@farmfe/core/dist/server/error.js:74:15)
    at Server.compile (file:///C:/Users/CEO/Desktop/izum_C/farm-project/node_modules/.deno/@farmfe+core@1.6.6/node_modules/@farmfe/core/dist/server/index.js:63:29)
    at async Server.listen (file:///C:/Users/CEO/Desktop/izum_C/farm-project/node_modules/.deno/@farmfe+core@1.6.6/node_modules/@farmfe/core/dist/server/index.js:45:9)
    at async start (file:///C:/Users/CEO/Desktop/izum_C/farm-project/node_modules/.deno/@farmfe+core@1.6.6/node_modules/@farmfe/core/dist/index.js:35:9)
    at async handleAsyncOperationErrors (file:///C:/Users/CEO/Desktop/izum_C/farm-project/node_modules/.deno/@farmfe+cli@1.0.4/node_modules/@farmfe/cli/dist/utils.js:111:9)
~/Desktop/izum_C/farm-project> ls                                                             1 01/23/2025 02:07:41 下午╭────┬────────────────────┬──────┬─────────┬───────────────╮
│  # │        name        │ type │  size   │   modified    │
├────┼────────────────────┼──────┼─────────┼───────────────┤
│  0 │ .gitignore         │ file │   257 B │ 6 minutes ago │
│  1 │ README.md          │ file │   438 B │ 6 minutes ago │
│  2 │ deno.lock          │ file │ 81.1 KB │ 6 minutes ago │
│  3 │ farm.config.ts     │ file │   147 B │ 6 minutes ago │
│  4 │ index.html         │ file │   349 B │ 6 minutes ago │
│  5 │ node_modules       │ dir  │  4.1 KB │ 6 minutes ago │
│  6 │ package.json       │ file │   418 B │ 6 minutes ago │
│  7 │ public             │ dir  │     0 B │ 6 minutes ago │
│  8 │ src                │ dir  │  4.1 KB │ 6 minutes ago │
│  9 │ tsconfig.json      │ file │   667 B │ 6 minutes ago │
│ 10 │ tsconfig.node.json │ file │   244 B │ 6 minutes ago │
╰────┴────────────────────┴──────┴─────────┴───────────────╯
~/Desktop/izum_C/farm-project>

**Comment by izumkineno** [comment]
this is an rsbuild project with the same command in the same environment
     __  ,
 .--()°'.' Welcome to Nushell,
'|, . ,'   based on the nu language,
 !_-(_\    where all data is structured!

Please join our Discord community at https://discord.gg/NtAbbGn
Our GitHub repository is at https://github.com/nushell/nushell
Our Documentation is located at https://nushell.sh
Tweet us at @nu_shell
Learn how to remove this at: https://nushell.sh/book/configuration.html#remove-welcome-message

It's been this long since Nushell's first commit:
5yrs 8months 12days 13hrs 12mins 952ms 938µs 200ns

~/Desktop/izum_C> npm create rsbuild@latest                                                     01/23/2025 02:11:12 下午

◆  Create Rsbuild Project
│
◇  Project name or path
│
◇  Select framework
│  Vue 3
│
◇  Select language
│  TypeScript
│
◇  Select additional tools (Use <space> to select, <enter> to continue)
│  none
│
◇  Next steps ─────────╮
│                      │
│  cd rsbuild_project  │
│  npm install         │
│  npm run dev         │
│                      │
├──────────────────────╯
│
└  Done.

~/Desktop/izum_C> cd rsbuild_project\                                                           01/23/2025 02:11:40 下午~/Desktop/izum_C/rsbuild_project> deno i                                                        01/23/2025 02:11:42 下午Warning The following packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed:
┠─ npm:core-js@3.40.0
┃
┠─ This may cause the packages to not work correctly.
┖─ To run lifecycle scripts, use the `--allow-scripts` flag with `deno install`:
   deno install --allow-scripts=npm:core-js@3.40.0
~/Desktop/izum_C/rsbuild_project> deno run dev                                                  01/23/2025 02:11:46 下午Task dev rsbuild dev --open

  Rsbuild v1.2.1

  ➜ Network:  http://172.16.29.1:3000/
  ➜ Network:  http://172.16.138.1:3000/
  ➜ Local:    http://localhost:3000/
  ➜ Network:  http://192.168.1.100:3000/
  ➜ press h + enter to show shortcuts

start   Building...
ready   Built in 0.26 s (web)




I am curious what is the reason why deno cannot run in the farm project

**Comment by wre232114** [comment]
We'll take a look

**Comment by shulandmimi** [comment]
@izumkineno I tried to follow your reproduction steps but the issue did not occur. Could you please provide your environment information and upload your project?

```
PS C:\path\to\_2073> npx envinfo --system --npmPackages @farmfe/core --npmPackages @farmfe/cli --binaries --browsers

  System:
    OS: Windows 11 10.0.22621
    CPU: (32) x64 Intel(R) Core(TM) i9-14900HX
    Memory: 17.09 GB / 31.73 GB
  Binaries:
    Node: 21.7.3 - ~\AppData\Local\fnm_multishells\17856_1737864618713\node.EXE
    npm: 10.5.0 - ~\AppData\Local\fnm_multishells\17856_1737864618713\npm.CMD
    pnpm: 9.4.0 - ~\AppData\Local\fnm_multishells\17856_1737864618713\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (127.0.2651.86)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @farmfe/cli: 1.0.4 => 1.0.4 
    @farmfe/core: 1.6.6 => 1.6.6 

PS C:\path\to\_2073> deno -v
deno 2.1.7
PS C:\path\to\_2073> deno run dev  
Task dev farm start
[ Farm ] Using config file at C:\path\to\_2073\farm.config.ts

 ϟ  Farm  v1.6.6
 ✓  Ready in 107ms ⚡️FULL EXTREME! 

[ Farm ] > Local:   http://localhost:9000/
```

**Comment by izumkineno** [comment]
> [@izumkineno](https://github.com/izumkineno) I tried to follow your reproduction steps but the issue did not occur. Could you please provide your environment information and upload your project?
> 
> ```
> PS C:\path\to\_2073> npx envinfo --system --npmPackages @farmfe/core --npmPackages @farmfe/cli --binaries --browsers
> 
>   System:
>     OS: Windows 11 10.0.22621
>     CPU: (32) x64 Intel(R) Core(TM) i9-14900HX
>     Memory: 17.09 GB / 31.73 GB
>   Binaries:
>     Node: 21.7.3 - ~\AppData\Local\fnm_multishells\17856_1737864618713\node.EXE
>     npm: 10.5.0 - ~\AppData\Local\fnm_multishells\17856_1737864618713\npm.CMD
>     pnpm: 9.4.0 - ~\AppData\Local\fnm_multishells\17856_1737864618713\pnpm.CMD
>   Browsers:
>     Edge: Spartan (44.22621.2134.0), Chromium (127.0.2651.86)
>     Internet Explorer: 11.0.22621.1
>   npmPackages:
>     @farmfe/cli: 1.0.4 => 1.0.4 
>     @farmfe/core: 1.6.6 => 1.6.6 
> 
> PS C:\path\to\_2073> deno -v
> deno 2.1.7
> PS C:\path\to\_2073> deno run dev  
> Task dev farm start
> [ Farm ] Using config file at C:\path\to\_2073\farm.config.ts
> 
>  ϟ  Farm  v1.6.6
>  ✓  Ready in 107ms ⚡️FULL EXTREME! 
> 
> [ Farm ] > Local:   http://localhost:9000/
> ```

C:\Users\CEO>npx envinfo --system --npmPackages @farmfe/core --npmPackages @farmfe/cli --binaries --browsers
Need to install the following packages:
  envinfo@7.14.0
Ok to proceed? (y) y

  System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400F
    Memory: 6.60 GB / 15.82 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.5 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.2 - ~\AppData\Local\pnpm\pnpm.CMD
    bun: 1.2.0 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.86)
    Internet Explorer: 11.0.22621.3527

npm notice
npm notice New major version of npm available! 9.6.5 -> 11.1.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.1.0
npm notice Run npm install -g npm@11.1.0 to update!
npm notice

C:\Users\CEO>deno -v
deno 2.1.5

**Comment by bitsnaps** [comment]
Tried this command:
```bash
deno run -RWE npm:farm@latest farm-app --template react
```
Which is almost identical to [vite](https://docs.deno.com/deploy/tutorials/vite/)'s equivalent command to create a Deno project with Vite, but I get this error:
```
error: Failed resolving binary export. '/Users/mac/Library/Caches/deno/npm/registry.npmjs.org/farm/0.0.1/package.json' did not have a bin property
```
I thought farm will play well with [deno](https://github.com/denoland/deno/issues/20375), since it doesn't rely on esbuild!

**Comment by shulandmimi** [comment]
@bitsnaps It looks like you are creating a farm application. The CLI for creating a farm application is [create-farm](https://www.npmjs.com/package/create-farm?activeTab=readme).

You can use Deno like this:

> However, there seems to be an issue with the Deno runtime, as it cannot correctly accept arguments.

```sh
deno run -RWE npm:create-farm@latest --template react
```

Other package managers can be used like this:

```sh
pnpm create farm
```

**Comment by bitsnaps** [comment]
@shulandmimi Thanks! I just had to install `npm:core-js` after that (as suggested by deno) as follows: 
```bash
deno install --allow-scripts=npm:core-js@3.40.0
```
I didn't see `create-farm` on the [quick-start](https://www.farmfe.org/docs/quick-start)'s page, it should definitely be added, I tried multiple commands I found on that page, however, the bundle size for vue3 hello project is almost **164Mb** !

**Comment by shulandmimi** [comment]
@bitsnaps 

1. Yes, we will update the command for creating projects with Deno in the quick-start guide later. Thank you for your reminder.
2. 164MB, I think you are referring to the size of the node_modules. It is relatively normal for modern projects as it includes a lot of code for handling frameworks.

**Comment by viscropst** [comment]
At deno 2.4.5,When I creating a project by running the `create-farm` with project name, It's shows `error: unexpected argument 'deno-vue2' found`. Without project name it's working fine.
```
PS D:\DevStation\profile\vscode_work> deno run -A npm:create-farm --template vue2 deno-vue2
error: unexpected argument 'deno-vue2' found

Usage: create-farm [OPTIONS] [PROJECT_NAME]

For more information, try '--help'.
PS D:\DevStation\profile\vscode_work> 
```

**Comment by viscropst** [comment]
Here is the steps when I `create-farm` without project name.
```
PS D:\DevStation\profile\vscode_work> deno run -A npm:create-farm --template vue2

 ⚡ Welcome To Farm ! 


 ✔️ Template copied Successfully! 


 >  Initial Farm Project created successfully ✨ ✨ 

    cd create-farm 

    npm install 

    npm run dev 

PS D:\DevStation\profile\vscode_work> cd .\create-farm\
PS D:\DevStation\profile\vscode_work\create-farm> deno install
Warning The following packages are deprecated:
┖─ npm:vue@2.7.16 (Vue 2 has reached EOL and is no longer actively maintained. See https://v2.vuejs.org/eol/ for more details.)
Warning The following packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed:
┠─ npm:core-js@3.45.0
┃
┠─ This may cause the packages to not work correctly.
┖─ To run lifecycle scripts, use the `--allow-scripts` flag with `deno install`:
   deno install --allow-scripts=npm:core-js@3.45.0
Packages: 327
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Resolved: 436, reused: 327, downloaded: 0, added: 327

Dependencies:
+ npm:vue 2.7.16

Dev dependencies:
+ npm:@farmfe/cli 1.0.5
+ npm:@farmfe/core 1.7.11
+ npm:@vitejs/plugin-vue2 2.3.3
+ npm:core-js 3.45.0
+ npm:vue-template-compiler 2.7.16
PS D:\DevStation\profile\vscode_work\create-farm> deno task start
Task start farm start
[ Farm ] Using config file at D:\DevStation\profile\vscode_work\create-farm\farm.config.ts
                                                                                                                                                                                                                                                                                 
 ϟ  Farm  v1.7.11
 ✓  Ready in 132ms ⚡️FULL EXTREME! 

[ Farm ] > Local:   http://localhost:9000/
[ Farm ] > Network: http://192.168.20.125:9000/
^C终止批处理操作吗(Y/N)? y
PS D:\DevStation\profile\vscode_work\create-farm> deno task build
Task build farm build
[ Farm ] Using config file at D:\DevStation\profile\vscode_work\create-farm\farm.config.ts
[ Farm ] Build completed in 404ms ⚡️FULL EXTREME! Resources emitted to ./dist.                                                                                                                                                                                                   
[ Farm ] Error: Error copying public directory: Cannot copy 'D:\DevStation\profile\vscode_work\create-farm\public\favicon.ico' to a subdirectory of itself, 'dist\favicon.ico'.
PS D:\DevStation\profile\vscode_work\create-farm> deno task
Available tasks:
- dev (package.json)
    farm start
- start (package.json)
    farm start
- build (package.json)
    farm build
- preview (package.json)
    farm preview
- clean (package.json)
    farm clean
PS D:\DevStation\profile\vscode_work\create-farm>
```

**Comment by bitsnaps** [comment]
> Here is the steps when I `create-farm` without project name.
> 
> ```
> PS D:\DevStation\profile\vscode_work> deno run -A npm:create-farm --template vue2


Replace `vue2` by `vue3`:
```
deno run -RWE npm:create-farm@latest --template vue3
# then select "A" for "All"
cd create-farm
deno install
```
The project get's created, but when run it with `deno run dev` I get:
```
[ Farm ] Error: Failed to start the server
Caused by: Error: Vite plugin vite:vue is not compatible with Farm for now. Because it uses hook "shouldTransformCachedM
```
Here is how I fixed it:
2- Remove broken dependency:
```
deno uninstall npm:@vitejs/plugin-vue
```

3- Install compatible package [unplugin-vue](https://www.npmjs.com/package/unplugin-vue) according to this: [#2137](https://github.com/farm-fe/farm/issues/2137):
```
deno install npm:unplugin-vue
```
4- Update `farm.config.ts` file:
```js
import { defineConfig } from '@farmfe/core';
//import vue from '@vitejs/plugin-vue'; // <-- Remove this
import Vue from 'unplugin-vue/farm';

export default defineConfig({
  plugins: [Vue()] // <-- Update this
});
```
then run the project:
```
deno run dev
```
You should be able to see the app running on: `http://localhost:9000`.
Tested with `deno 2.4.5`.

**Comment by viscropst** [comment]
> > Here is the steps when I `create-farm` without project name.
> > ```
> > PS D:\DevStation\profile\vscode_work> deno run -A npm:create-farm --template vue2
> > ```
> 
> Replace `vue2` by `vue3`:
> 
> ```
> deno run -RWE npm:create-farm@latest --template vue3
> # then select "A" for "All"
> cd create-farm
> deno install
> ```
> 
> The project get's created, but when run it with `deno run dev` I get:
> 
> ```
> [ Farm ] Error: Failed to start the server
> Caused by: Error: Vite plugin vite:vue is not compatible with Farm for now. Because it uses hook "shouldTransformCachedM
> ```
> 
> Here is how I fixed it: 2- Remove broken dependency:
> 
> ```
> deno uninstall npm:@vitejs/plugin-vue
> ```
> 
> 3- Install compatible package [unplugin-vue](https://www.npmjs.com/package/unplugin-vue) according to this: [#2137](https://github.com/farm-fe/farm/issues/2137):
> 
> ```
> deno install npm:unplugin-vue
> ```
> 
> 4- Update `farm.config.ts` file:
> 
> import { defineConfig } from '@farmfe/core';
> //import vue from '@vitejs/plugin-vue'; // <-- Remove this
> import Vue from 'unplugin-vue/farm';
> 
> export default defineConfig({
>   plugins: [Vue()] // <-- Update this
> });
> 
> then run the project:
> 
> ```
> deno run dev
> ```
> 
> You should be able to see the app running on: `http://localhost:9000`. Tested with `deno 2.4.5`.

I can running them normally without doing this fix step. My deno was fresh installed,and my environment has no npm,npx,but has bun installed.

<img width="1349" height="1284" alt="Image" src="https://github.com/user-attachments/assets/5b5c5e30-9097-4ff3-82f6-56a2598ad8a0" />

**Comment by viscropst** [comment]
Here is my steps. But path prefix problem of `deno task build` and uncaught error with`deno task preview` still exists.
```
PS D:\DevStation\profile\vscode_work> deno run -RWE npm:create-farm --template vue3
✅ Granted ffi access to "D:\DevStation\runtimes\_cache\deno\npm\registry.npmmirror.com\create-farm-win32-x64-msvc\0.0.21\create-farm.win32-x64-msvc.node".

 ⚡ Welcome To Farm !


 ✔️ Template copied Successfully! 


 >  Initial Farm Project created successfully ✨ ✨

    cd create-farm

    npm install

    npm run dev

PS D:\DevStation\profile\vscode_work> cd .\create-farm\
PS D:\DevStation\profile\vscode_work\create-farm> deno install
Warning The following packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed:
┠─ npm:core-js@3.45.0
┃
┠─ This may cause the packages to not work correctly.
┖─ To run lifecycle scripts, use the `--allow-scripts` flag with `deno install`:
   deno install --allow-scripts=npm:core-js@3.45.0
Packages: 332
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Resolved: 438, reused: 332, downloaded: 0, added: 332

Dependencies:
+ npm:vue 3.5.18

Dev dependencies:
+ npm:@farmfe/cli 1.0.5
+ npm:@farmfe/core 1.7.11
+ npm:@vitejs/plugin-vue 5.0.4
+ npm:core-js 3.45.0
PS D:\DevStation\profile\vscode_work\create-farm> deno run dev
Task dev farm start
[ Farm ] Using config file at D:\DevStation\profile\vscode_work\create-farm\farm.config.ts
                                                                                                                                                                                                                        
 ϟ  Farm  v1.7.11
 ✓  Ready in 468ms ⚡️FULL EXTREME! 

[ Farm ] > Local:   http://localhost:9000/
[ Farm ] > Network: http://192.168.20.125:9000/
^C终止批处理操作吗(Y/N)? y
PS D:\DevStation\profile\vscode_work\create-farm> deno task build                            
Task build farm build
[ Farm ] Using config file at D:\DevStation\profile\vscode_work\create-farm\farm.config.ts
[ Farm ] Build completed in 425ms ⚡️FULL EXTREME! Resources emitted to ./dist.                                                                                                                                          
[ Farm ] Error: Error copying public directory: Cannot copy 'D:\DevStation\profile\vscode_work\create-farm\public\favicon.ico' to a subdirectory of itself, 'dist\favicon.ico'.
PS D:\DevStation\profile\vscode_work\create-farm> 
```
Here is `deno task preview` output
```
PS D:\DevStation\profile\vscode_work\create-farm> deno run -A npm:@farmfe/cli preview            
[ Farm ] Using config file at D:\DevStation\profile\vscode_work\create-farm\farm.config.ts
error: Uncaught AddrInUse: 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。 (os error 10048)
    at listen (ext:deno_net/01_net.js:594:35)
    at serveInner (ext:deno_http/00_serve.ts:710:16)
    at serve (ext:deno_http/00_serve.ts:627:10)
    at ServerImpl._serve (node:http:1562:22)
    at node:http:1506:23
    at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:28:11)
    at eventLoopTick (ext:core/01_core.js:176:29)
PS D:\DevStation\profile\vscode_work\create-farm> deno run -RWE npm:@farmfe/cli preview          
✅ Granted all ffi access.
✅ Granted all sys access.
[ Farm ] Using config file at D:\DevStation\profile\vscode_work\create-farm\farm.config.ts
✅ Granted all net access.
error: Uncaught AddrInUse: 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。 (os error 10048)
    at listen (ext:deno_net/01_net.js:594:35)
    at serveInner (ext:deno_http/00_serve.ts:710:16)
    at serve (ext:deno_http/00_serve.ts:627:10)
    at ServerImpl._serve (node:http:1562:22)
    at node:http:1506:23
    at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:28:11)
    at eventLoopTick (ext:core/01_core.js:176:29)
PS D:\DevStation\profile\vscode_work\create-farm> deno run -RWE npm:@farmfe/cli preview
✅ Granted all ffi access.
✅ Granted all sys access.
[ Farm ] Using config file at D:\DevStation\profile\vscode_work\create-farm\farm.config.ts
❌ Denied net access to "0.0.0.0:1911".
[ Farm ] Error: Error in httpServer: NotCapable: Requires net access to "0.0.0.0:1911", run again with the --allow-net flag
[ Farm ] Error: Failed to start preview server:
undefined
PS D:\DevStation\profile\vscode_work\create-farm> 
```

**Comment by wre232114** [comment]
You can try upgrade `@farmfe/cli` and `@farmfe/core` to `2.0.0@beta`, which solve the vite plugin compatibility issue and other issues you mentioned above

**Comment by viscropst** [comment]
Okay, I'll have a try.

**Comment by viscropst** [comment]
> Here is my steps. But path prefix problem of `deno task build` and uncaught error with`deno task preview` still exists.
> 
> ```
> PS D:\DevStation\profile\vscode_work> deno run -RWE npm:create-farm --template vue3
> ✅ Granted ffi access to "D:\DevStation\runtimes\_cache\deno\npm\registry.npmmirror.com\create-farm-win32-x64-msvc\0.0.21\create-farm.win32-x64-msvc.node".
> 
>  ⚡ Welcome To Farm !
> 
> 
>  ✔️ Template copied Successfully! 
> 
> 
>  >  Initial Farm Project created successfully ✨ ✨
> 
>     cd create-farm
> 
>     npm install
> 
>     npm run dev
> 
> PS D:\DevStation\profile\vscode_work> cd .\create-farm\
> PS D:\DevStation\profile\vscode_work\create-farm> deno install
> Warning The following packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed:
> ┠─ npm:core-js@3.45.0
> ┃
> ┠─ This may cause the packages to not work correctly.
> ┖─ To run lifecycle scripts, use the `--allow-scripts` flag with `deno install`:
>    deno install --allow-scripts=npm:core-js@3.45.0
> Packages: 332
> ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> Resolved: 438, reused: 332, downloaded: 0, added: 332
> 
> Dependencies:
> + npm:vue 3.5.18
> 
> Dev dependencies:
> + npm:@farmfe/cli 1.0.5
> + npm:@farmfe/core 1.7.11
> + npm:@vitejs/plugin-vue 5.0.4
> + npm:core-js 3.45.0
> PS D:\DevStation\profile\vscode_work\create-farm> deno run dev
> Task dev farm start
> [ Farm ] Using config file at D:\DevStation\profile\vscode_work\create-farm\farm.config.ts
>                                                                                                                                                                                                                         
>  ϟ  Farm  v1.7.11
>  ✓  Ready in 468ms ⚡️FULL EXTREME! 
> 
> [ Farm ] > Local:   http://localhost:9000/
> [ Farm ] > Network: http://192.168.20.125:9000/
> ^C终止批处理操作吗(Y/N)? y
> PS D:\DevStation\profile\vscode_work\create-farm> deno task build                            
> Task build farm build
> [ Farm ] Using config file at D:\DevStation\profile\vscode_work\create-farm\farm.config.ts
> [ Farm ] Build completed in 425ms ⚡️FULL EXTREME! Resources emitted to ./dist.                                                                                                                                          
> [ Farm ] Error: Error copying public directory: Cannot copy 'D:\DevStation\profile\vscode_work\create-farm\public\favicon.ico' to a subdirectory of itself, 'dist\favicon.ico'.
> PS D:\DevStation\profile\vscode_work\create-farm> 
> ```
> 
> Here is `deno task preview` output
> 
> ```
> PS D:\DevStation\profile\vscode_work\create-farm> deno run -A npm:@farmfe/cli preview            
> [ Farm ] Using config file at D:\DevStation\profile\vscode_work\create-farm\farm.config.ts
> error: Uncaught AddrInUse: 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。 (os error 10048)
>     at listen (ext:deno_net/01_net.js:594:35)
>     at serveInner (ext:deno_http/00_serve.ts:710:16)
>     at serve (ext:deno_http/00_serve.ts:627:10)
>     at ServerImpl._serve (node:http:1562:22)
>     at node:http:1506:23
>     at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:28:11)
>     at eventLoopTick (ext:core/01_core.js:176:29)
> PS D:\DevStation\profile\vscode_work\create-farm> deno run -RWE npm:@farmfe/cli preview          
> ✅ Granted all ffi access.
> ✅ Granted all sys access.
> [ Farm ] Using config file at D:\DevStation\profile\vscode_work\create-farm\farm.config.ts
> ✅ Granted all net access.
> error: Uncaught AddrInUse: 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。 (os error 10048)
>     at listen (ext:deno_net/01_net.js:594:35)
>     at serveInner (ext:deno_http/00_serve.ts:710:16)
>     at serve (ext:deno_http/00_serve.ts:627:10)
>     at ServerImpl._serve (node:http:1562:22)
>     at node:http:1506:23
>     at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:28:11)
>     at eventLoopTick (ext:core/01_core.js:176:29)
> PS D:\DevStation\profile\vscode_work\create-farm> deno run -RWE npm:@farmfe/cli preview
> ✅ Granted all ffi access.
> ✅ Granted all sys access.
> [ Farm ] Using config file at D:\DevStation\profile\vscode_work\create-farm\farm.config.ts
> ❌ Denied net access to "0.0.0.0:1911".
> [ Farm ] Error: Error in httpServer: NotCapable: Requires net access to "0.0.0.0:1911", run again with the --allow-net flag
> [ Farm ] Error: Failed to start preview server:
> undefined
> PS D:\DevStation\profile\vscode_work\create-farm> 
> ```
The problem quoted above is resolved after upgrading to `@farmfe/core@2.0.0-beta.3` and `@farmfe/cli@2.0.0-beta.0`.
```
PS D:\DevStation\profile\vscode_work\create-farm> deno install npm:@farmfe/core@2.0.0-beta.3 -D
Add npm:@farmfe/core@2.0.0-beta.3
Warning The following packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed:
┠─ npm:core-js@3.45.1
┃
┠─ This may cause the packages to not work correctly.
┖─ To run lifecycle scripts, use the `--allow-scripts` flag with `deno install`:
   deno install --allow-scripts=npm:core-js@3.45.1
PS D:\DevStation\profile\vscode_work\create-farm> deno install npm:@farmfe/cli@2.0.0-beta.0 -D 
Add npm:@farmfe/cli@2.0.0-beta.0
Warning The following packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed:
┠─ npm:core-js@3.45.1
┃
┠─ This may cause the packages to not work correctly.
┖─ To run lifecycle scripts, use the `--allow-scripts` flag with `deno install`:
   deno install --allow-scripts=npm:core-js@3.45.1
PS D:\DevStation\profile\vscode_work\create-farm> deno task build
Task build farm build
[ building ] ⠂                                                                                                                   
[ Farm ] Using config file at D:\DevStation\profile\vscode_work\create-farm\farm.config.ts
[ building ] ⢀ render farm_internal_runtime_index                                                                                
Output files:

File                                           Size          Gzipped   
dist/farm.c71c631e.js                          2.7 KB        1.2 KB      
dist/farm.df1a4e17.js                          108 B         91 B        
dist/index.410cb52d.js                         36.5 KB       15.1 KB     
dist/index.7422d592.js                         5.9 KB        2.8 KB      
dist/index.b77e3208.css                        1.3 KB        709 B       
dist/index.d9c6c75c.js                         21.4 KB       8.1 KB      
dist/index.f8ded2db.js                         1.6 KB        943 B       
dist/index.html                                608 B         312 B       
dist/logo.e052fe17-7e9d40.png                  16.5 KB       16.4 KB     
dist/vue.5532db34-7fc44e.svg                   496 B         315 B       

Total:
  Size: 87.1 KB
  Gzipped: 45.9 KB

[ Farm ] Build completed in 765ms ⚡️FULL EXTREME! Resources emitted to ./dist.
PS D:\DevStation\profile\vscode_work\create-farm> deno task preview
Task preview farm preview
[ Farm ] Using config file at D:\DevStation\profile\vscode_work\create-farm\farm.config.ts

 ϟ  Farm  v2.0.0-beta.3

[ Farm ] ➜  Local:   http://127.0.0.1:1911/
[ Farm ] ➜  Network: http://192.168.20.125:1911/
终止批处理操作吗(Y/N)? y
PS D:\DevStation\profile\vscode_work\create-farm> 
```

**Comment by viscropst** [comment]
But I found a new problem with `create-farm@2.0.0-beta.0` with following output.
```
PS D:\DevStation\profile\vscode_work\create-farm> deno run -A npm:create-farm@2.0.0-beta.0 --template vue2
Warning The following packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed:
┠─ npm:core-js@3.45.1
┃
┠─ This may cause the packages to not work correctly.
┠─ Lifecycle scripts are only supported when using a `node_modules` directory.
┠─ Enable it in your deno config file:
┖─ "nodeModulesDir": "auto"
error: Uncaught (in promise) Error: Cannot find module 'create-farm-win32-x64-msvc'
Require stack:
- D:\DevStation\runtimes\_cache\deno\npm\registry.npmmirror.com\create-farm\2.0.0-beta.0\index.js
- D:\DevStation\runtimes\_cache\deno\npm\registry.npmmirror.com\create-farm\2.0.0-beta.0\create-farm.js
    at Module._resolveFilename (node:module:635:15)
    at Module._load (node:module:498:27)
    at Module.require (node:module:696:19)
    at require (node:module:830:16)
    at file:///D:/DevStation/runtimes/_cache/deno/npm/registry.npmmirror.com/create-farm/2.0.0-beta.0/index.js:71:29
    at Object.<anonymous> (file:///D:/DevStation/runtimes/_cache/deno/npm/registry.npmmirror.com/create-farm/2.0.0-beta.0/index.js:316:3)
    at Module._compile (node:module:759:34)
    at loadMaybeCjs (node:module:784:10)
    at Object.Module._extensions..js (node:module:769:12)
    at Module.load (node:module:677:32)
PS D:\DevStation\profile\vscode_work\create-farm>
```

**Comment by shulandmimi** [comment]
> But I found a new problem with `create-farm@2.0.0-beta.0` with following output.
> 
> ```
> PS D:\DevStation\profile\vscode_work\create-farm> deno run -A npm:create-farm@2.0.0-beta.0 --template vue2
> Warning The following packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed:
> ┠─ npm:core-js@3.45.1
> ┃
> ┠─ This may cause the packages to not work correctly.
> ┠─ Lifecycle scripts are only supported when using a `node_modules` directory.
> ┠─ Enable it in your deno config file:
> ┖─ "nodeModulesDir": "auto"
> error: Uncaught (in promise) Error: Cannot find module 'create-farm-win32-x64-msvc'
> Require stack:
> - D:\DevStation\runtimes\_cache\deno\npm\registry.npmmirror.com\create-farm\2.0.0-beta.0\index.js
> - D:\DevStation\runtimes\_cache\deno\npm\registry.npmmirror.com\create-farm\2.0.0-beta.0\create-farm.js
>     at Module._resolveFilename (node:module:635:15)
>     at Module._load (node:module:498:27)
>     at Module.require (node:module:696:19)
>     at require (node:module:830:16)
>     at file:///D:/DevStation/runtimes/_cache/deno/npm/registry.npmmirror.com/create-farm/2.0.0-beta.0/index.js:71:29
>     at Object.<anonymous> (file:///D:/DevStation/runtimes/_cache/deno/npm/registry.npmmirror.com/create-farm/2.0.0-beta.0/index.js:316:3)
>     at Module._compile (node:module:759:34)
>     at loadMaybeCjs (node:module:784:10)
>     at Object.Module._extensions..js (node:module:769:12)
>     at Module.load (node:module:677:32)
> PS D:\DevStation\profile\vscode_work\create-farm>
> ```

Trtry it
it's work on my macos

<img width="1642" height="666" alt="Image" src="https://github.com/user-attachments/assets/7580666e-4d45-469d-b0e9-82da5e0c6c0d" />

**Comment by viscropst** [comment]
> > But I found a new problem with `create-farm@2.0.0-beta.0` with following output.
> > ```
> > PS D:\DevStation\profile\vscode_work\create-farm> deno run -A npm:create-farm@2.0.0-beta.0 --template vue2
> > Warning The following packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed:
> > ┠─ npm:core-js@3.45.1
> > ┃
> > ┠─ This may cause the packages to not work correctly.
> > ┠─ Lifecycle scripts are only supported when using a `node_modules` directory.
> > ┠─ Enable it in your deno config file:
> > ┖─ "nodeModulesDir": "auto"
> > error: Uncaught (in promise) Error: Cannot find module 'create-farm-win32-x64-msvc'
> > Require stack:
> > - D:\DevStation\runtimes\_cache\deno\npm\registry.npmmirror.com\create-farm\2.0.0-beta.0\index.js
> > - D:\DevStation\runtimes\_cache\deno\npm\registry.npmmirror.com\create-farm\2.0.0-beta.0\create-farm.js
> >     at Module._resolveFilename (node:module:635:15)
> >     at Module._load (node:module:498:27)
> >     at Module.require (node:module:696:19)
> >     at require (node:module:830:16)
> >     at file:///D:/DevStation/runtimes/_cache/deno/npm/registry.npmmirror.com/create-farm/2.0.0-beta.0/index.js:71:29
> >     at Object.<anonymous> (file:///D:/DevStation/runtimes/_cache/deno/npm/registry.npmmirror.com/create-farm/2.0.0-beta.0/index.js:316:3)
> >     at Module._compile (node:module:759:34)
> >     at loadMaybeCjs (node:module:784:10)
> >     at Object.Module._extensions..js (node:module:769:12)
> >     at Module.load (node:module:677:32)
> > PS D:\DevStation\profile\vscode_work\create-farm>
> > ```
> 
> Trtry it it's work on my macos
> <img alt="Image" width="1642" height="666" src="https://private-user-images.githubusercontent.com/45983040/490991970-7580666e-4d45-469d-b0e9-82da5e0c6c0d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTgyNDgwODQsIm5iZiI6MTc1ODI0Nzc4NCwicGF0aCI6Ii80NTk4MzA0MC80OTA5OTE5NzAtNzU4MDY2NmUtNGQ0NS00NjlkLWIwZTktODJkYTVlMGM2YzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTE5VDAyMDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZDhjNjI3ZTc0ZjdhYzhmZjUyZmM1OTgxMDhkNTZkODEwNjI5MDIzMWNiNGEyODNhMTIxNWY4MWEwNjVlNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rG4RnVWevQvYjzyZtvkQQmj5kLc--AIIjqQmgncc-IM">

But windows is not working. Is `create-farm@2.0.0-beta.0` has built for windows x64 msvc?
```
PS D:\DevStation\profile\vscode_work> deno clean
Removed D:\DevStation\runtimes\_cache\deno (64639 files, 840.35MB)
PS D:\DevStation\profile\vscode_work> deno run -A npm:create-farm@2.0.0-beta.0 --template vue2
error: Uncaught (in promise) Error: Cannot find module 'create-farm-win32-x64-msvc'
Require stack:
- D:\DevStation\runtimes\_cache\deno\npm\registry.npmmirror.com\create-farm\2.0.0-beta.0\index.js
- D:\DevStation\runtimes\_cache\deno\npm\registry.npmmirror.com\create-farm\2.0.0-beta.0\create-farm.js
    at Module._resolveFilename (node:module:635:15)
    at Module._load (node:module:498:27)
    at Module.require (node:module:696:19)
    at require (node:module:830:16)
    at file:///D:/DevStation/runtimes/_cache/deno/npm/registry.npmmirror.com/create-farm/2.0.0-beta.0/index.js:71:29
    at Object.<anonymous> (file:///D:/DevStation/runtimes/_cache/deno/npm/registry.npmmirror.com/create-farm/2.0.0-beta.0/index.js:316:3)
    at Module._compile (node:module:759:34)
    at loadMaybeCjs (node:module:784:10)
    at Object.Module._extensions..js (node:module:769:12)
    at Module.load (node:module:677:32)
PS D:\DevStation\profile\vscode_work> 
```

**Comment by overby-me** [comment]
@viscropst Have you considered Windows Subsystem for Linux (WSL)?

**Comment by viscropst** [comment]
No, because the latest version can running `create-farm` normally,but `2.0.0-beta.0` cannot running it. So it's no need to use WSL.
And below is the npm cache of deno (executed `deno run -A npm:create-farm@2.0.0-beta.0 --template vue2` after running `deno clean`).
<img width="1616" height="853" alt="Image" src="https://github.com/user-attachments/assets/f372c716-359b-435c-8b8c-9bb2890ca882" />

**Comment by viscropst** [comment]
> No, because the latest version can running `create-farm` normally,but `2.0.0-beta.0` cannot running it. So it's no need to use WSL. And below is the npm cache of deno (executed `deno run -A npm:create-farm@2.0.0-beta.0 --template vue2` after running `deno clean`). <img alt="Image" width="1616" height="853" src="https://private-user-images.githubusercontent.com/16207250/491850652-f372c716-359b-435c-8b8c-9bb2890ca882.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg1MDEyNTgsIm5iZiI6MTc1ODUwMDk1OCwicGF0aCI6Ii8xNjIwNzI1MC80OTE4NTA2NTItZjM3MmM3MTYtMzU5Yi00MzVjLThiOGMtOWJiMjg5MGNhODgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTIyVDAwMjkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYWFhMzAxZjgwZjM3NzY0M2YwNzFiODlkNDVkNGYyOGM0Y2FjZWViZWMzODA2ZjE4ZWUzYWUzOWM1NzJmYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mUJ44vS6x3DI5IqhEweuZtigzNNa1bSxOV3ByIMNsLE">

`create-farm@2.0.0-beta.1` is normally running for windows.
<img width="1230" height="365" alt="Image" src="https://github.com/user-attachments/assets/4ed03727-a03f-4623-a8fc-fec073b763f5" />

**Comment by viscropst** [comment]
> At deno 2.4.5,When I creating a project by running the `create-farm` with project name, It's shows `error: unexpected argument 'deno-vue2' found`. Without project name it's working fine.
> 
> ```
> PS D:\DevStation\profile\vscode_work> deno run -A npm:create-farm --template vue2 deno-vue2
> error: unexpected argument 'deno-vue2' found
> 
> Usage: create-farm [OPTIONS] [PROJECT_NAME]
> 
> For more information, try '--help'.
> PS D:\DevStation\profile\vscode_work> 
> ```

But this problem was not fixed.
```
PS D:\DevStation\profile> deno clean                                     
Removed D:\DevStation\runtimes\_cache\deno (8546 files, 111.19MB)
PS D:\DevStation\profile> deno run -A npm:create-farm@2.0.0-beta.1 --help
Create Farm cli tool

Usage: create-farm [OPTIONS] [PROJECT_NAME]

Arguments:
  [PROJECT_NAME]  Project name

Options:
  -m, --manager <MANAGER>    Package manager to use
  -t, --template <TEMPLATE>  Project template to use
  -f, --force                Force overwrite of existing files
  -h, --help                 Print help
  -V, --version              Print version
PS D:\DevStation\profile> deno run -A npm:create-farm@2.0.0-beta.1 --template vue2 farm-vue2
error: unexpected argument 'farm-vue2' found

Usage: create-farm [OPTIONS] [PROJECT_NAME]

For more information, try '--help'.
PS D:\DevStation\profile> 
```

**Comment by viscropst** [comment]
I used the latest beta of `create-farm`, but still not working in windows.

<img width="1113" height="626" alt="Image" src="https://github.com/user-attachments/assets/5e7128dc-fa7d-4449-831a-348ae40fb425" />

**Comment by shulandmimi** [comment]
> I used the latest beta of `create-farm`, but still not working in windows.
> 
> <img alt="Image" width="1113" height="626" src="https://private-user-images.githubusercontent.com/16207250/503034977-5e7128dc-fa7d-4449-831a-348ae40fb425.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjEwMjk1NzcsIm5iZiI6MTc2MTAyOTI3NywicGF0aCI6Ii8xNjIwNzI1MC81MDMwMzQ5NzctNWU3MTI4ZGMtZmE3ZC00NDQ5LTgzMWEtMzQ4YWU0MGZiNDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDIxVDA2NDc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZWFiMTE1MzE4ZjI4ZGYwYWI2YmIyZjhmZTIwOTVkNDkzNzE4ZTU2MjVmNDdmMWY1YjU4ZjdmMmQ3OTQ4ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eXOzDoCQ8hpWOANmnsMwkkqOOsuBTf2IQKrAqTtbv64">

It seems that I didn't test all the shells sufficiently, I will try cmd, powershell on windows again today, thank you

**Comment by viscropst** [comment]
> I used the latest beta of `create-farm`, but still not working in windows.
> <img alt="Image" width="1113" height="626" src="https://private-user-images.githubusercontent.com/16207250/503034977-5e7128dc-fa7d-4449-831a-348ae40fb425.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM5NjEwMzgsIm5iZiI6MTc2Mzk2MDczOCwicGF0aCI6Ii8xNjIwNzI1MC81MDMwMzQ5NzctNWU3MTI4ZGMtZmE3ZC00NDQ5LTgzMWEtMzQ4YWU0MGZiNDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTI0VDA1MDUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YzkxYWVkYTEzYWJhNmNhZjU0NDBmODI5ZjgwYzczNGRhMGMyMmYxMzUwOGZhOWNhYzE3ZWFiYzU2M2ViOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NJsAvc4wjvad3O4RdQl_rdCN7fv7YGc61CoK3lhJGnY">

The latest beta(2.0.0-beta.3) is working on windows. Here are screenshot of cmd,nushell and powershell.

For CMD:

<img width="1113" height="740" alt="Image" src="https://github.com/user-attachments/assets/bd098850-4990-477a-b7c2-4187e8bdd560" />

For Powershell:

<img width="1113" height="892" alt="Image" src="https://github.com/user-attachments/assets/1eda308a-0593-47c9-92b9-357df46233b9" />

For Nushell:

<img width="1113" height="1215" alt="Image" src="https://github.com/user-attachments/assets/21cee4f5-1fc0-4c24-8ffa-70149ce72d6f" />
